#nullable disable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using System.ComponentModel;
using System.Xml.Serialization;

namespace Schematron.Serialization;

/// <summary>
/// <remarks>
/// This code was generated by VS Paste Special Xml to Class. It therefore may feel like overkill and a poor model to support deserialization operations
/// </remarks>
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public class SchematronValidationResultTempObjectModel
{
    [XmlType(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
    [XmlRoot(ElementName = "output", Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron", IsNullable = false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record Output
    {
        [XmlElement("xml")]
        public OutputXml Xml { get; set; }
        [XmlElement("schematron")]
        public OutputSchematron Schematron { get; set; }
    }

    [XmlType(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record OutputXml
    {
        [XmlElement("xmlSchema")]
        public OutputXmlXmlSchema XmlSchema { get; set; }
        [XmlElement("message")]
        public OutputXmlMessage Message { get; set; }
    }

    [XmlType(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record OutputXmlXmlSchema
    {
        [XmlAttribute("id")]
        public string Id { get; set; }

        [XmlAttribute("version")]
        public string Version { get; set; }

        [XmlAttribute("targetNamespace")]
        public string TargetNamespace { get; set; }
    }

    [XmlType(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record OutputXmlMessage
    {
        [XmlElement("text")]
        public string Text { get; set; }
        [XmlElement("position")]
        public OutputXmlMessagePosition Position { get; set; }
    }

    [XmlType(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record OutputXmlMessagePosition
    {
        [XmlAttribute("line")]
        public byte Line { get; set; }

        [XmlAttribute("column")]
        public byte Column { get; set; }
    }

    [XmlType(AnonymousType = true, Namespace = "http://sourceforge.net/projects/dotnetopensrc/schematron")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record OutputSchematron
    {
        [XmlElement("schema", Namespace = "")]
        public Schema Schema { get; set; }
    }

    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record Schema
    {
        [XmlElement("phase")]
        public SchemaPhase Phase { get; set; }

        [XmlAttribute("title")]
        public string Title { get; set; }
    }

    [XmlType(AnonymousType = true)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record SchemaPhase
    {
        [XmlElement("pattern")]
        public SchemaPhasePattern[] Pattern { get; set; }

        [XmlAttribute("id")]
        public string Id { get; set; }
    }

    [XmlType(AnonymousType = true)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record SchemaPhasePattern
    {
        [XmlElement("rule")]
        public SchemaPhasePatternRule Rule { get; set; }

        [XmlAttribute("name")]
        public string Name { get; set; }

        [XmlAttribute("id")]
        public string Id { get; set; }
    }

    [XmlType(AnonymousType = true)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record SchemaPhasePatternRule
    {
        [XmlAttribute("id")]
        public string Id { get; set; }

        [XmlElement("message")]
        public SchemaPhasePatternRuleMessage[] Message { get; set; }

        [XmlAttribute("context")]
        public string Context { get; set; }
    }

    [XmlType(AnonymousType = true)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record SchemaPhasePatternRuleMessage
    {
        [XmlElement("text")]
        public string Text { get; set; }
        [XmlElement("path")]
        public string Path { get; set; }
        [XmlElement("summary")]
        public object Summary { get; set; }
        [XmlElement("position")]
        public SchemaPhasePatternRuleMessagePosition Position { get; set; }
    }

    [XmlType(AnonymousType = true)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public record SchemaPhasePatternRuleMessagePosition
    {
        [XmlAttribute("line")]
        public byte Line { get; set; }

        [XmlAttribute("column")]
        public byte Column { get; set; }
    }
}

